"""empty message

Revision ID: 69241992de47
Revises: 
Create Date: 2023-05-31 12:44:54.952564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69241992de47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('date_updated')

    # ### end Alembic commands ###
