"""empty message

Revision ID: d41ef4b7f9b9
Revises: 7d9804e46927
Create Date: 2023-05-31 15:46:15.399172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd41ef4b7f9b9'
down_revision = '7d9804e46927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_deadline', sa.String(length=150), nullable=True))
        batch_op.drop_column('deadline_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadline_date', sa.VARCHAR(length=150), nullable=True))
        batch_op.drop_column('date_deadline')

    # ### end Alembic commands ###
